### ISSUE TITLE
Exporting the model

### ISSUE THREAD

**Issue by ConProgramming** [ramsrigouthamg/Paraphrase-any-question-with-T5-Text-To-Text-Transfer-Transformer-#1]
This is a great model and the Jupyter notebook is super helpful! Inference works great in the notebook, but I'm curious if you could help me figure out how to export the model so I can use it with ONNX, or Pytorch mobile, etc.

**Comment by ramsrigouthamg** [comment]
Hi @ConProgramming , Once you load the model, in the code do model.save_pretrained("./new_name").
It should save the model in the new_name folder. It is just a PyTorch model. In the new_name folder, you will perhaps see a .json and .bin file. So you can use ONNX runtime or any other just like how you deal with other Pytorch models.

Similarly, when loading you can use model = XXXX.from_pretrained("./new_name""), to load a model from local directory.
Let me know if it helped.

**Comment by ConProgramming** [comment]
> Hi @ConProgramming , Once you load the model, in the code do model.save_pretrained("./new_name").
> 
> It should save the model in the new_name folder. It is just a PyTorch model. In the new_name folder, you will perhaps see a .json and .bin file. So you can use ONNX runtime or any other just like how you deal with other Pytorch models.
> 
> 
> 
> Similarly, when loading you can use model = XXXX.from_pretrained("./new_name""), to load a model from local directory.
> 
> Let me know if it helped. 

Thanks for the help! Ive already gotten to saving it and loading it back up for basic inferencing, but Im having trouble saving it to be used with onnyx or any other mobile/web platform. Was wondering if you'd been able to do this?

**Comment by ramsrigouthamg** [comment]
Hi @ConProgramming , I see! Sorry, I haven't explored further.

**Comment by ConProgramming** [comment]
Ah okay thanks anyways. Ill submit a PR with information if I can figure it out 👍.

**Comment by ramsrigouthamg** [comment]
Sounds good! Thanks!
