### ISSUE TITLE
t5-base model download

### ISSUE THREAD

**Issue by inidhinarayan** [ramsrigouthamg/Paraphrase-any-question-with-T5-Text-To-Text-Transfer-Transformer-#2]
Hi 
This solution is really helpful. But unfortunately due to proxy issues on my workstation, the t5-base model is not getting downloaded. I have downloaded the model and .bin files manually from s3 and huggingface. Any idea on how it can be linked. I am still getting an error: 
OSError: Model name 't5-base' was not found in tokenizers model name list

**Comment by ramsrigouthamg** [comment]
hi @inidhinarayan !
You can load model like this model = T5ForConditionalGeneration.from_pretrained('./yourFoldername')
**yourFoldername** is the folder that has the .bin and .config files you downloaded from the S3.

Use the same line 
 tokenizer = T5Tokenizer.from_pretrained('t5-base')  
If not try 't5-small' etc. Don't load the tokenizer from **yourFoldername**. Use teh above line itself.

**Comment by inidhinarayan** [comment]
hi @ramsrigouthamg 
Thanks for the solution. Also, I was facing issues gpu memory allocation issue while running this with torch, even when my GPU memory is free. I have tried using gc.collect() as well as deleting the cached memory. I also tried reducing the batch length to 4 and max length to 128. But the problem persists. My config:
**Ubuntu 20.04
Nvidia GeForce GTX 1050-Ti
Cuda 10.1**

`RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.95 GiB total capacity; 3.07 GiB already allocated; 9.25 MiB free; 3.16 GiB reserved in total by PyTorch)
`

**Comment by ramsrigouthamg** [comment]
Hi @inidhinarayan ,
See if you can reduce to batch size to 2, and you can also try the t5-small model instead of T5-base.
I use p2xlarge on AWS. You can also try google colab.

**Comment by inidhinarayan** [comment]
Thanks a ton @ramsrigouthamg ! I was finally able to run the model with the modifications, though not on local but colab.

**Comment by ramsrigolla** [comment]
@inidhinarayan Awesome! Glad that you could get it to work. Cheers!

**Comment by ramsrigouthamg** [comment]
@inidhinarayan Awesome! Glad that you could get it to work. Cheers!
