### ISSUE TITLE
Failed to run train.py

### ISSUE THREAD

**Issue by lilakk** [ramsrigouthamg/Paraphrase-any-question-with-T5-Text-To-Text-Transfer-Transformer-#3]
I need to retrain this model on a paraphrase dataset that is non-question-based for research purposes. I got the following errors when I ran train.py. I have Python 3.7.6, torch 1.5.1, transformers 3.0.2, pytorch_lightning 0.8.5.

RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.

BrokenPipeError: [Errno 32] Broken pipe

**Comment by lilakk** [comment]
After I downgraded torch, transformers and pytorch_lightning to the required versions, I still got the RuntimeError.
![error](https://user-images.githubusercontent.com/19506523/88240618-a1610d00-cc55-11ea-8419-c6e31f980c9b.PNG)

**Comment by ramsrigouthamg** [comment]
Hi @EllaChang , Can you look into it here https://github.com/pytorch/pytorch/issues/5858

Looks like you need to add "torch.multiprocessing.freeze_support()" in the main function that is called.
Also, look into arguments to disable multiprocessing if it is causing error.

What is the GPU you are using? And where are you running this? (Local/ Google colab/ AWS)?

**Comment by EllaChang** [comment]
> Hi @EllaChang , Can you look into it here [pytorch/pytorch#5858](https://github.com/pytorch/pytorch/issues/5858)
> 
> Looks like you need to add "torch.multiprocessing.freeze_support()" in the main function that is called.
> Also, look into arguments to disable multiprocessing if it is causing error.
> 
> What is the GPU you are using? And where are you running this? (Local/ Google colab/ AWS)?
