### ISSUE TITLE
Determine probability of two texts being paraphrases of each other?

### ISSUE THREAD

**Issue by styfeng** [ramsrigouthamg/Paraphrase-any-question-with-T5-Text-To-Text-Transfer-Transformer-#8]
Hi there, 

I am wondering if it's possible to use this to determine the probability of two texts being paraphrases of each other, rather than for paraphrase generation? 

Thanks,
Steven

**Comment by ramsrigouthamg** [comment]
Hi @styfeng  BERT and similar models like Roberta etc can be used for classification. 
It is a problem better suited for that not generation.
